config/routes.rb
Rails.application.routes.draw do
    root 'welcome#index'
    resources :contacts, only:[:new, :create]

end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name, validate: true
		attribute :email, validate: true, email: true
		attribute :message, validate: true
		attribute :telephone, validate: true
		attribute :zipcode, captcha: true

	def headers
		{
			:subject => "brandfieldadvertising Contact Form",
			:to => "allan@brandfieldadvertising.com",
			:from => %("#{name}" <#{email}>)

		}

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
   def new
    @contact = Contact.new
    end

    def create
      @contact = Contact.new(params[:contact])
      @contact.request = request
      if @contact.deliver
        flash.now[:error]=nil
      else
        flash.now[:error]="Cannot send message for some reason"
        render :new
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <p class="lead">Thanks a lot for contacting us we shall get back to you as soon as possible.</p>
        <%= link_to "<< Return to home page",  root_path,class:'btn btn-warning btn-lg pull-right'%>
      </div>
    </div>

  </div>
</section>

app/views/contacts/new.html.erb
<%= render 'layouts/contact'%>

app/views/layouts/_contact.html.erb

   <section id="contact" class="contact-section text-center">
     <div class="container">
               <h2 class="section-title">Contact Us</h2>
               <div class="contact-intro">
                 <p>Please get in touch with us and our dedicated team wil get back to you as soon as possible. We are appreciate you contacting us..</p>
               </div>
               <ul class="contact-info-list list-inline">
                 <li class="item">
                   <span class="custom-icon icon-telephone_signal"></span>
                   <span class="info"><a href="#">01234 555 666</a></span>
                 </li>
                 <li class="item">
                   <span class="custom-icon icon-email"></span>
                   <span class="info"><a href="#">info@yourwebsite.com</a></span>
                 </li>
               </ul>

               <%= form_for @contact do |f| %>
                   <section id="contact-form" class="contact-form form">
                     <div id="form-messages" class="text-center "></div>
                     <div id="form-messages" class="text-center"></div>
                     <div class="row text-left">
                      <% if @contact.errors.any? %>
                          <div id="error_explanation"class="alert alert-danger alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this mail from being sent.</h2>

                            <ul>
                              <% @contact.errors.full_messages.each do |message| %>
                                  <li><%= message %></li>
                              <% end %>
                            </ul>
                          </div>
                      <% end %>

                   <div class="name-group col-sm-6 col-xs-12 form-group">
                      <div class="form-group-inner">
                        <%= f.label :name %>
                        <%= f.text_field :name, class:'form-control' %>
                      </div>
                   </div>
                    <div class="name-group col-sm-6 col-xs-12 form-group">
                                <div class="form-group-inner">
                        <%= f.label :email%>
                        <%= f.email_field :email, class:'form-control' %>
                     </div>
                     </div>
                     <div class="name-group col-sm-12 col-xs-12 form-group">
                       <div class="form-group-inner">
                          <%= f.label :telephone%>
                          <%= f.text_field :telephone, class:'form-control' %>
                       </div>
                     </div>
                      <div class="name-group col-sm-6 col-xs-12 form-group hidden">
                                <div class="form-group-inner">
                        <%= f.label :zipcode %>
                        <%= f.text_field :zipcode,class:'form-control' %>
                      </div>
                      </div>

                       <div class="name-group col-sm-12 col-xs-12 form-group">
                         <div class="form-group-inner">
                        <%= f.label :message %>
                        <%= f.text_area :message, class:'form-control', rows:'10' %>
                          </div>

                      </div>
                     <div class="col-xs-12 form-group">
                      <div class="actions">
                        <%= f.submit 'Send Message', class: 'btn btn-primary btn-lg pull-right' %>
                      </div>
                    </div>
                        </div>
                  </section>
                </div>
            </section>
       <% end %>


app/views/layouts/_footer.html.erb
    <!-- ******FOOTER****** --> 
    <footer class="footer">
        <div class="footer-main container">
            <div class="row">
                <div class="footer-col business-hours-col col-md-4 col-sm-6 col-xs-12">
                    <h3 class="col-title">Business Hours</h3>
                    <div class="intro">We are open Monday to Saturday. <br>Come visit us in our office.</div>
                    <ul class="business-hours-list list-unstyled">
                        <li><strong>Monday - Friday:</strong> 8am - 6pm</li>
                        <li><strong>Saturday:</strong> 9am - 4pm</li>
                        <li><strong>Sunday:</strong> Closed</li>
                    </ul>
                </div><!--//footer-col-->
                <div class="footer-col contact-us-col col-md-4 col-sm-6 col-xs-12">
                    <h3 class="col-title">Contact Us</h3>
                    <ul class="footer-contact-list list-unstyled">
                        <li class="item">
                            <span class="custom-icon icon-telephone_signal"></span>
                            <span class="info"><a href="#">+256773333893</a></span>
                        </li>
                        <li class="item">
                            <span class="custom-icon icon-email"></span>
                            <span class="info"><a href="#">allan@brandfieldadvertising.com</a></span>
                        </li>    
                        <li class="item">
                            <span class="custom-icon icon-map_pin"></span>
                            <span class="info">
                                
                                    <span class="street-address">Bukoto</span><br>
                                    <span class="region">Namuli Road</span><br>
                                    <span class="postal-code">Kampala</span><br>
                                    <span class="country-name">Uganda</span>
                               
                            </span>
                        </li>    
                    </ul>
                </div><!--//footer-col-->
                <div class="footer-col follow-us-col col-md-4 col-xs-12">
                    <h3 class="col-title">Follow Us</h3>
                    <div class="intro">Follow us on our social media handles indicated below.</div>
                    <div class="social-container">
                        <ul class="list-inline social-list">
                            <li class="social-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li class="social-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li class="social-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
                            <li class="social-item"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul><!--//social-list-->
                    </div><!--//social-container-->
                    
                     <ul class="footer-menu list-unstyled">
                        <li><a href="#">Terms &amp; Conditions</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div><!--//footer-col-->
            </div><!--//row-->
            
           
            
        </div><!--//container-->
        <div class="bottombar text-center">
                
                
                <div class="copyright">&copy;2016Railsshop. LTD <a href="https://www.therailsshop.club" target="_blank">Therailsshop</a></div>  
                
        </div><!--//bottombar--> 
    </footer><!--//footer-->

app/views/layouts/_header.html.erb


   
    
    <!-- ******HEADER****** --> 
    <header id="header" class="header">  
        <div id="topbar" class="topbar">
            <div class="container-fluid">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header text-center">
                        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                            <span class="icon-bar-wrapper">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </span><!--//icon-bar-wrapper-->
                        </button><!--//nav-toggle-->
                    </div><!--//navbar-header-->
                    <div id="navbar-collapse" class="navbar-collapse collapse text-center">
                        <ul class="nav navbar-nav center-block">
                            <li class="nav-item active"><%= link_to "Home",root_path%></li>
                            <li class="nav-item"><a class="scrollto" href="#services">Services</a></li>
                            <li class="nav-item"><a class="scrollto" href="#why">Why Us</a></li>  
                            <li class="nav-item"><a class="scrollto" href="#reviews">Reviews</a></li>
                            <li class="nav-item"><a class="scrollto" href="#about">About</a></li> 
                            <li class="nav-item"><a class="scrollto" href="#projects">Projects</a></li>                                     
<!--                            <li class="nav-item"><a class="scrollto" href="#shop">Shop</a></li>-->
                            <li class="nav-item"><a class="scrollto" href="#faqs">FAQs</a></li>
                            <li class="nav-item"><%= link_to "Contact us", new_contact_path%></li>
                        </ul><!--//nav-->
                    </div><!--//navabr-collapse-->
                </nav><!--//main-nav-->
                <div class="social-container">
                    <ul class="list-inline social-list">
                        <li class="social-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li class="social-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li class="social-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li class="social-item"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    </ul><!--//social-list-->
                </div><!--//social-container-->
            </div><!--//container-->
        </div><!--//topbar-->
        <div class="branding container">    
            <h1 class="logo pull-left"><img id="logo-image" class="logo-image" src="/assets/images/brandfieldlogo2.png" alt="brandfieldlogo"></h1> 
            <ul class="header-info-list list-inline pull-right">
                <li class="info-item contact-methods">
                    <span class="custom-icon icon-telephone_signal"></span>
                    <span class="info-main phone-number"><a href="#">0773333893</a></span>
                    <span class="info-sub"><a href="#">allan@brandadvertising.com</a></span>
                </li><!--//info-item-->
                <li class="info-item business-hours">
                    <span class="custom-icon icon-clock"></span>
                    <span class="info-main phone-number">8am - 6pm</span>
                    <span class="info-sub">Monday - Saturday</span>
                </li><!--//info-item-->
            </ul><!--//info-list-->
        </div><!--//branding-->
    </header><!--//header-->

app/views/layouts/_scripts.html.erb
 <!-- Main Javascript -->          
    <script type="text/javascript" src="/assets/plugins/jquery-1.12.3.min.js"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/assets/plugins/jquery-scrollTo/jquery.scrollTo.min.js"></script>  
    <script type="text/javascript" src="/assets/plugins/jquery-match-height/jquery.matchHeight-min.js"></script>
    <script type="text/javascript" src="/assets/plugins/jquery.validate.min.js"></script> 
    <script type="text/javascript" src="/assets/plugins/jquery-inview/jquery.inview.min.js"></script>
    <script type="text/javascript" src="/assets/plugins/isMobile/isMobile.min.js"></script>   
    <script type="text/javascript" src="/assets/plugins/back-to-top.js"></script>
    <script type="text/javascript" src="/assets/plugins/owl-carousel/owl.carousel.min.js"></script> 
    <script type="text/javascript" src="/assets/plugins/Gallery/js/jquery.blueimp-gallery.min.js"></script>
    <script type="text/javascript" src="/assets/plugins/Bootstrap-Image-Gallery/js/bootstrap-image-gallery.min.js"></script>
    <script type="text/javascript" src="/assets/js/ajax-form.js"></script> 
    
    <script type="text/javascript" src="/assets/js/main.js"></script> 
    
    <!--[if !IE]>-->
    <script type="text/javascript" src="/assets/js/animations.js"></script> 
    <!--<![endif]--> 
        
    <!-- Style Switcher (REMOVE ON YOUR PRODUCTION SITE) -->
    <script src="/assets/js/demo/style-switcher.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->  
    <!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->  
    <!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->  
    <head>
        <title>Brandfield Advertising</title>
        <!-- Meta -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">    
        <link rel="shortcut icon" href="favicon.ico">  
        <link href='https://fonts.googleapis.com/css?family=Lato:400,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>
        <!-- Global CSS -->
        <link rel="stylesheet" href="/assets/plugins/bootstrap/css/bootstrap.min.css">   
        <!-- Plugins CSS -->   
        <link rel="stylesheet" href="/assets/plugins/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="/assets/plugins/custom-icons/style.css">
        <link rel="stylesheet" href="/assets/plugins/animate-css/animate.min.css">
        <link rel="stylesheet" href="/assets/plugins/owl-carousel/assets/owl.carousel.min.css">
        <link rel="stylesheet" href="/assets/plugins/owl-carousel/assets/owl.theme.default.min.css">
        <link rel="stylesheet" href="/assets/plugins/Gallery/css/blueimp-gallery.min.css">
        <link rel="stylesheet" href="/assets/plugins/Bootstrap-Image-Gallery/css/bootstrap-image-gallery.min.css">
        
        <!-- Theme CSS -->
        <link id="theme-style" rel="stylesheet" href="/assets/css/styles-2.css">
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    	  <%= stylesheet_link_tag    'application', media: 'all'%>
    	  <%= javascript_include_tag 'application' %>
    	  <%= csrf_meta_tags %>
        
    </head> 
     
    <body data-spy="scroll">  
       <% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
                <div class="alert alert-<%= name.to_s == 'notice' ? "success" : "danger"  %> alert-dismissable" >
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times; </button>
                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                </div>
            <% end %>
    <% end %>
        <%= render 'layouts/header'%>
            <%= yield %>
        <%= render 'layouts/footer'%>    
        <%= render 'layouts/scripts'%>
    </body>
</html>